name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: aadilshaikh123
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#00F5FF&color_dots=#0D1117,#161B22,#21262D,#30363D,#484F58,#6E7681,#7D8590,#8B949E,#B1BAC4,#F0F6FC
            dist/github-snake-neon.svg?color_snake=#00F5FF&color_dots=#0A0A0B,#1A1A2E,#16213E,#0F3460,#533A7B,#7209B7,#A663CC,#4FC3F7,#29B6F6,#03DAC6

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
